baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Devlog'
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params.homeInfoParams]
  Title = "Hi there wave"
  Content = "Can be Info, links, about..."
